How to specify an engine's URI loaction
ember-engines/ember-engines.com pull request #11
Opened 2016-12-19 07:52 UTC by meori

I'll try and document obstacles I tackle while I implement engines for our app.

2016-12-22 16:51 UTC, trentmwillis requested changes
Looking good, thanks for the PR! Some minor tweaks I'd like to see before merging.

2016-12-22 16:51 UTC, trentmwillis commented on markdown/guide/deploying-engines.md
> +In many cases, the engine code will be served from a static server, typically a CDN.
We keep paragraphs on a single line, so can you combine these down?

2016-12-22 16:51 UTC, trentmwillis commented on markdown/guide/deploying-engines.md
> +In order to specify the engine's assets location, you can implement a `generateURI` function at the host application's build options file:
The phrase "engine's assets location" reads a little odd to me, can we rephrase just as "engine asset location"?

Also, let's change "at the host application's build options file" to "in the host application's `ember-cli-build.js`"

2016-12-22 16:51 UTC, trentmwillis commented on markdown/guide/deploying-engines.md
> +The `generateURI` function receives the `filePath` for each asset and must return a string of the asset's location.
Need a newline before this paragraph. Also, let's add a link to the `ember-asset-loader` documentation here. Maybe: `For more info, see the [ember-asset-loader documentation](https://github.com/ember-engines/ember-asset-loader#generating-custom-uris)`

2016-12-22 16:51 UTC, trentmwillis commented on markdown/guide/deploying-engines.md
> +
Should delete this line.

2016-12-24 02:14 UTC, meori commented
Fixed the text. Hope it works for you :)

2016-12-24 15:00 UTC, trentmwillis approved these changes

2016-12-24 15:06 UTC, merged