link-to doesn't work without a second parameter
ember-engines/ember-engines.com pull request #33
Opened 2017-09-26 12:09 UTC by lordblendi

If you use a link-to without "yield", you have to provide two parameters:
- name of the route
- text to show

So the example of `{{link-to-external "home"}}` won't work until you give one more parameter:
`{{link-to-external "home" "home"}}`

2017-09-26 20:38 UTC, trentmwillis requested changes
Good catch! One small tweak request to make it clearer, but thanks for the contribution!

2017-09-26 20:38 UTC, trentmwillis commented on markdown/guide/linking-and-external-links.md
> +{{link-to-external "home" "home"}}
Can we use "Go Home" (or something similar) as the second parameter? That way it will be more clear what each argument is doing.

2017-09-27 08:31 UTC, lordblendi commented
Yes, I just added a new commit with it. Also realized I messed up the order:
- the first is the text to show
- the second is the route

I tested it in my engine application :) Sorry for the confusion.

2017-09-27 18:46 UTC, trentmwillis approved these changes
Thanks!

2017-09-27 18:46 UTC, merged